### ISSUE TITLE
Wrong url in hourly forecast ?

### ISSUE THREAD

**Issue by elkjaerit** [Kayxue/AccuWeatherAPIWrapper#1]
Hi, 

I'm trying to get a 12 hour forecast, but it's not working - I'm getting an 401 error (which I think is also wrong, but thats a problem in the AccuWeather API...)

According to the AccuWeather API spec the url for getting hourly forecasts is 'http://dataservice.accuweather.com/forecasts/v1/hourly/{hours}hour/{location}. 

I think the problem is a wrong url in the getHourlyForecast method: "_/**daily**/${hours}hour/${locationKey}_"

https://github.com/Kayxue/AccuWeatherAPIWrapper/blob/master/src/API/ForecastAPIClient.js#L53

Can you have a look ?

**Comment by Kayxue** [comment]
OK I'll check that

**Comment by Kayxue** [comment]
Fixed with  [c11633e](https://github.com/Kayxue/AccuWeatherAPIWrapper/commit/c11633e6336845d9f384386765f1620515358212), released as v1.1.0
